#!/bin/bash

docker pull homeassistant/home-assistant:stable
docker pull vaultwarden/server:latest
docker pull nextcloud:apache
docker pull redis:alpine
docker pull postgres:14-alpine
docker pull postgres:13-alpine

