name: build
on: push

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: More disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          export VERSION=3.10.0
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce_${VERSION}-focal_amd64.deb
          sudo dpkg -i singularity-ce_${VERSION}-focal_amd64.deb
          df -h

      - name: Restart docker daemon with experimental feature
        run: |
          tmp=$(mktemp)
          sudo jq '.+{experimental:true}' /etc/docker/daemon.json > "$tmp"
          sudo mv "$tmp" /etc/docker/daemon.json
          sudo systemctl restart docker.service

      - name: Build
        run: |
          TZ="Asia/Shanghai"
          tag=$(date +'%Y.%m.%d')
          for app in test
          do
            docker build --rm --no-cache --squash -t lanfanb/$app:$tag -f $app.Dockerfile .
            singularity build $app.$tag.sif docker-daemon://lanfanb/$app:$tag
            tar -cJvf $app.$tag.sif.tar.xz $app.$tag.sif
          done

      - name: Upload test
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: test.*.sif.tar.xz
          
